package enums;

public enum eshape {
	POWER_SOURCE, ACCUMULATION_ELEMENT, CONVERSION_ELEMENT, COUPLING_ELEMENT, SWITCHING_ELEMENT, AMPLIFICATION_ELEMENT, 
	INVERSION_CONVERSION_ELEMENT, INVERSION_ACCUMULATION_ELEMENT, INVERSION_COUPLING_ELEMENT, INVERSION_AMPLIFICATION_ELEMENT, 
	INVERSION_SWITCHING_ELEMENT, CONTROL_STRATEGY;
}
